
development:
  adapter: postgresql
  encoding: unicode
  database: MCV_development
  pool: 5
  username: postgres 
  password: alejo0906
  host: localhost
  port: 5432



test:
  adapter: postgresql
  encoding: unicode
  database: MCV_test
  pool: 5
  username: postgres 
  password: alejo0906
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: MCV_production
  pool: 5
  username: rails
  password: alejo0906
  host: localhost
  port: 5432
