# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4babfa00cb41d247084e035b3637dcc6899a720301758d6f102f3758a788df3781d0b1947fece2139b177d241a0bf0f584bbc302276d94c1fd67d69c0e56bb3c

test:
  secret_key_base: 42c2953f83d652b969b5fb625ac2b917ffb4e6f303c6b1e7baa081bdc66a1be07d5b94a30e81aee6cc4f1557f2dd4fa9b1af9461da0d6c8906907d943ea609c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
